services:
  js-app:
    build: ./frontend
    container_name: "webgame"
    ports:
      - '8030:8030'
      # - "3000:3000"
    volumes:
      - .:/app
    tty: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true