services:
  js-app:
    build: ./frontend
    container_name: "webgame"
    ports:
      - "3000:3000"     
      # - "6006:6006"
    volumes:
      - .:/app
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true